require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'script/*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'util/**/*'
  NewCops: enable

# Lint
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Max: 38

Metrics/ClassLength:
  CountComments: false
  Max: 650

Metrics/ModuleLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 80

Metrics/PerceivedComplexity:
  Max: 10

# Style
Style/Documentation:
  Enabled: false

Security/Eval:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false # skipping

Style/RaiseArgs:
  Enabled: false # skipping

Style/SignalException:
  Enabled: false # skipping

Style/GlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate: # seconds == 0
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

# layout
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# Naming
Naming/VariableNumber: # variables like space_1 or approval_02
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# Rails
Rails:
  Enabled: true

Output:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

# RSpec
RSpec/DescribedClass:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
